name: build-and-push-release-image

on:
  push:
    branches:
      # Run on pushing branches like `release/1.0.0`
      - "release/*.*.*"

jobs:
  build-and-push-release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Extract build args
        # Extract version from branch name
        # Example: branch name `release/1.0.0` sets up env.VERSION=1.0.0
        run: |
          echo "VERSION=${GITHUB_REF_NAME#release/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: spf20081
          password: Qq2290903617


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: shipeng101
          password: Spf20081.
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          version: v0.9.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            usememos/memos:test
            ghcr.io/usememos/memos
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ env.VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.VERSION }}
            type=semver,pattern={{major}},value=${{ env.VERSION }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
