name: Docker Build and Push
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Docker
        run: |
          sudo apt update && sudo apt install docker.io -y
        
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: spf20081
          DOCKER_PASSWORD: Qq2290903617.
        run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
          
      - name: Build and push image
        run: |
          docker build . -t your-image-tag
          docker push spfnas
